# Generated by Django 5.2.6 on 2025-10-09 05:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='profile_images/default', max_length=255, null=True, verbose_name='image'),
        ),
    ]
