# Generated by Django 5.2.6 on 2025-10-10 04:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_images/vt7vpmt0jpiapfyws2bh', max_length=255, null=True, verbose_name='image'),
        ),
    ]
