# Generated by Django 5.2.6 on 2025-12-28 07:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_profile.png', max_length=255, null=True, verbose_name='profile_image'),
        ),
    ]
